### ISSUE TITLE
Transformer Scaling

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/transformer#100]
The transformer currently seems to be a bottleneck in the system. As observed in the ticket here: #89 the P99 is above 15 secs for 9k clients. Currently, there is some CPU headspace available on the server but a single instance of transformer is not able to utilize the entire resources of the system.

Initial steps:

- [ ] Create multiple instances of transformer on the same server.
    - [ ] Make sure all the instances are able to consume data from Kafka.
    - [ ] Each topic needs to have more than 1 partition to enable multiple instances to consume from the same topic.

**Comment by aakashyadav-kgp** [comment]
We observed prod server performing not as good as staging. Even with 1 instance the CPU usage is spiking to 100%. On staging we could deploy 2 instances and still reached 70% usage. 
@singhalkarun to help with this.

**Comment by aakashyadav-kgp** [comment]
Closing this ticket as it is tracked in #89
