### ISSUE TITLE
[Bug] Header issue - 1 message header is wrong

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/transformer#59]
Getting this error on the production server in the transformer.

transformer_1            | 2023-04-03 08:18:25.964  INFO 1 --- [nio-9091-exec-3] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
transformer_1            |  Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
transformer_1            |
transformer_1            | java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x000x850x010x000x000x810x030x03_0xdb0x1a0x9e8_AP0xda0xf380xd9I0xbd20xf0$0xf4{380x07e0xb90x160x84A0xf10xb20xa990xff0x000x00 ]. HTTP method names must be tokens
transformer_1            | 	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419) ~[tomcat-embed-core-9.0.55.jar!/:na]
transformer_1            | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:269) ~[tomcat-embed-core-9.0.55.jar!/:na]
transformer_1            | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.55.jar!/:na]
transformer_1            | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) ~[tomcat-embed-core-9.0.55.jar!/:na]
transformer_1            | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722) ~[tomcat-embed-core-9.0.55.jar!/:na]
transformer_1            | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.55.jar!/:na]
transformer_1            | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.55.jar!/:na]
transformer_1            | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.55.jar!/:na]
transformer_1            | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.55.jar!/:na]
transformer_1            | 	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
transformer_1            |

**Comment by pankajjangid05** [comment]
I tried to reproduce this issue on my locally, but I was not able to generate it again.
