### ISSUE TITLE
Transformer stops abruptly in 2-3 days

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/transformer#87]
@pankajjangid05 please attach the details and your findings here.

**Comment by pankajjangid05** [comment]
Hey @chinmoy12c 

I have implemented a connection pool in the transformer service for the aggregate database and also included the necessary Maven dependencies. Could you please review this commit at the following [URL](https://github.com/samagra-comms/transformer/commit/25a5b7310ecf338c21351fd4893ae754cd0a3a44)
