### ISSUE TITLE
Resolve transformer memory leaks

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/transformer#90]
After the recent changes done in transformer to resolve the abrupt halt of bots, a few memory leaks have been observed. These memory leaks eventually fill up the direct memory and need to be resolved.

**Comment by pankajjangid05** [comment]
Getting Error on Prod : 

```
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 2023-08-03 06:26:04,491 ERROR [reactive-kafka-transformer-1] io.netty.util.ResourceLeakDetector:319: LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | Recent access records: 
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | Created at:
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.buffer.SimpleLeakAwareByteBuf.retainedSlice(SimpleLeakAwareByteBuf.java:57)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.handler.codec.LengthFieldBasedFrameDecoder.extractFrame(LengthFieldBasedFrameDecoder.java:498)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	<unknown class>.<unknown method>(Unknown Source)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:332)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	<unknown class>.<unknown method>(Unknown Source)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	<unknown class>.<unknown method>(Unknown Source)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	<unknown class>.<unknown method>(Unknown Source)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	<unknown class>.<unknown method>(Unknown Source)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
core_transformer.1.l7t29co2dguj@UCI-Docker-Swarm-Master    | 	java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by aakashyadav-kgp** [comment]
Not able to reproduce this error on staging and haven't received this issue on prod.

**Comment by aakashyadav-kgp** [comment]
@pankajjangid05  just now got the error

https://github.com/samagra-comms/transformer/assets/111346170/353736db-3008-48c0-8f43-e348c2c4b7d9

**Comment by aakashyadav-kgp** [comment]
New Findings: The issue is related to load handling. 

We are doing 2 things:
1. Find benchmark of current capacity.
2. Find method to expand. Chinmoy suggested transformer optimisation and then horizontal scaling.

**Comment by karntrehan** [comment]
Bug identified by @PANKAJ172 - Multiple insertions into the DB for each question? To continue debugging.

**Comment by chinmoy12c** [comment]
Action Item:

- [ ] Add a unique field to db directly and gracefully fail on multiple insertion.

**Comment by karntrehan** [comment]
If a unique field is added, existing ongoing conversations with duplicate keys would get deleted. Need to test if the form is restarted.

**Comment by pankajjangid05** [comment]
The form is not restarted after deleting all the questions and assessments. Added index on 3 columns (form_id, form_version, x_path) and some changes on the backend side.

**Comment by pankajjangid05** [comment]
We need to discuss with Chakshu about the assessment table data.

**Comment by pankajjangid05** [comment]
As discussed with @chinmoy12c  I am removing assessment insertion from transformer. after this change I will redeploy on staging and test, If the transformer works fine we can go live today.

**Comment by geeky-abhishek** [comment]
@pankajjangid05 will deploy the code  to staging with final changes

**Comment by chinmoy12c** [comment]
Has been observed again on prod, potential problematic function has been identified, need to reproduce in dev testing.

**Comment by aakashyadav-kgp** [comment]
Working on test case for requests from multiple topics. To check how many users facing this issue on prod.

**Comment by pankajjangid05** [comment]
Added caching in the findByPhoneNoAndBotFormName method while getting the message state from the formsdb. @chinmoy12c Can you please review this PR : https://github.com/samagra-comms/transformer/pull/101/files

**Comment by aakashyadav-kgp** [comment]
On prod we are getting memory leak issues as soon as we cap memory but the same is not observed on staging. @singhalkarun to help on this.

**Comment by pankajjangid05** [comment]
These are the reasons of the direct buffer memory issue : 



![Image](https://github.com/samagra-comms/transformer/assets/103931276/5019c322-bf02-480c-a66f-5262f7c78d6e)


Inside the container 

![Image](https://github.com/samagra-comms/transformer/assets/103931276/57ebf8dd-58bd-4076-9892-7a6efae582ec)


![Image](https://github.com/samagra-comms/transformer/assets/103931276/8bd0efaf-dc1c-4ff5-b1c2-b4da11b98703)

**Comment by pankajjangid05** [comment]
Today I have added these configurations for the direct buffer memory issue in the Dockerfile : ["-Dio.netty.maxDirectMemory=0","-Dio.netty.noPreferDirect=true","-XX:MaxDirectMemorySize=2048m"]

**Result:**  

We still getting the same issue(Direct Buffer Memory) after the stress test on prod.

**Comment by aakashyadav-kgp** [comment]
Plan is to implement dispose off disposables to avoid memory leakage.

**Comment by chinmoy12c** [comment]
This has been resolved with recent optimisations.
